#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE
server:
  port: 80
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
